### PR TITLE
Concrete Pyomo model -- DO NOT MERGE

### PR DESCRIPTION
**Pull request by jdherman**
@msdogan @mfefer over the past few days I've been working on a rewrite to address a couple of issues, inspired by what Max has been working on...
- iterative runs to remove debug flows
- avoiding reading/writing big files
- incorporate all of our different scripts into the same code base
- we need a way to do connected annual runs for the CEC project

To get this flexibility, we need to move more of the data manipulation into python and away from the command line. Pyomo lets you do this with concrete models (instead of abstract models).  I don't mean to dramatically change the way that we're doing things, but for the annual runs especially I think we need to go in this direction.

On this branch so far, here is what works:
- Debug flows removed automatically for small modifications. (For example the 82-year run with 10% inflow reduction fixes itself in 4 iterations / 4 hours on HPC1).
- No more *.dat or results.json files. The model can read directly from links.csv, and that is the only input requirement. Likewise the postprocessor runs automatically on the pyomo results, and the big json file is never printed. (I haven't done tests but hopefully this will improve the runtime).
- The annual connected runs with end-of-period storage are working. The model is feasible as long as the EOP values are taken from the original optimal 82-year run (but of course we want to change those..). Each year's results are appended to CSV files by the postprocessor.

Now for the bad part, that I need some input on:
- When we change the EOP constraints, either lower or higher, it is really tough to get rid of debug flows. It messes up everything. And we need to run in debug mode for every year separately ... so even if it can fix the debug flows for 1922, it still might break for 1923, and so on.
- The "unit cost" debug method that Mustafa came up with has been working well, but I'm not 100% sure that the debug flows are appearing in the network exactly where they are needed. For example, I'm seeing debug flows show up at nodes where the outgoing lower bound constraint is zero, which means it must be used further down in the network.
- The automatic debug method does not discriminate between different types of links. It will reduce carryover constraints, including dead pools, which we might want to avoid.

To get to the point: 
1. Are there specific types of links that we should target or avoid for removing debug flows? In a way that we could filter based on node names. For example if we want to avoid reducing carryover bounds, look for "SR_" ... etc. 
2. What is the most likely cause of infeasibilities when we try changing the initial and final storage values?

Thanks. I'll keep working on this branch, it's not cleaned up enough to merge yet.

### CODE REVIEW

**Comment by jdherman** [comment]
To give a sense of what this looks like, here's the main file to run annually:
```python
from pyomo.environ import *
import pandas as pd
from calvin import *

eop = None

for i in range(1922,2004):

  print('\nNow running WY %d' % i)

  calvin = CALVIN('calvin/data/annual/linksWY%d.csv' % i, ic=eop)
  # change stuff (optional)
  # calvin.inflow_multiplier(0.9)
  # calvin.eop_constraint_multiplier(0.0)
  
  # run in debug mode (runs multiple iterations until flows or removed or maxiter is reached)
  calvin.create_pyomo_model(debug_mode=True, debug_cost=2e6)
  calvin.solve_pyomo_model(solver='glpk', nproc=1, debug_mode=True, maxiter=15)

  # if it gets this far, run with debug mode removed
  calvin.create_pyomo_model(debug_mode=False)
  calvin.solve_pyomo_model(solver='glpk', nproc=1, debug_mode=False)

  # this will append pyomo results to CSV files, and return the EOP storage values for the next run
  eop = postprocess(calvin.df, calvin.model, 
                    resultdir='results-annual', annual=True) 

# this is only required as a separate step when running annual loop
aggregate_regions('results-annual')
```

Then running on the command line:
```
python main-annual.py

Now running WY 1922
Creating Pyomo Model (debug=True)
-----Solving Pyomo Model (debug=True)
Finished. Fixing debug flows...
SR_ML.1922-09-30_FINAL UB raised by 8.28 (0.28%)
SR_ML.1922-09-30_DBUGSNK.1922-09-30 UB raised by 8.28 (0.00%)
-----Solving Pyomo Model (debug=True)
Finished. Fixing debug flows...
All debug flows eliminated (iter=2, vol=16.56)
Creating Pyomo Model (debug=False)
-----Solving Pyomo Model (debug=False)
Optimal Solution Found (debug=False).

Now running WY 1923
[...]
```

**Comment by mfefer** [comment]
I really like what you did with this concrete model method! Seems like it will be much easier to manipulate the data. I'll play around with this to get a hang of the concrete model and create the changes necessary for implementing the different multiplier for each month.

**Comment by jdherman** [comment]
ok but don't do anything yet, I'm still working on it -- getting rid of debug flows isn't working quite right yet. I'll push a cleaned up version later this week (I hope).

you're right that the inflow multipliers should be much easier after this. I'm going to make a separate script `network_modifiers.py` with a bunch of functions like this.

**Comment by msdogan** [comment]
Thanks @jdherman this sounds great! To comment your a few points:

- Yes, EOP constraints are though especially when you change them. I was thinking maybe jumping into EOP penalty instead of making it hard constraint make our job easier. That way we will never get infeasibility due to EOP. I know we don't have penalty values yet, but we can put a dummy value, say current Lagrange multiplier from historical model. When we have actual values, we can replace it. Using penalties are our ultimate goal, right?
- For unit cost model, if every link has positive cost, and `DBUGSOURCE` and DBUGSINK` have high cost, debug flows should appear in their exact location, right? Because otherwise is more costly, and putting debug flow into exact location should result in a better (lower cost) solution. But, of course there could be cases I am missing. If there is an example where debug flows are not appearing in their exact location, we can try to find a solution.
- In the past I never had to reduce deadpool storage but it does not mean we won't have problem with those :) But I remember reducing EOP constraint, not deadpool. Based on my experience, most problematic constraints when you are reduce inflows are local depletion, environmental minimum flow requirements and end-of-period constraints for reservoirs.

1. I can provide a list of links with constraints that we should avoid reducing. Or maybe we can order them because if there is no other way to get a feasible run we have to reduce those constraints. Basically, I would try to reduce environmental flows (including fixed wildlife refuge deliveries), EOP constraints and local accretion/depletion first. And then deadpool and fixed urban deliveries. I will try to put together a list.

**Comment by jdherman** [comment]
Thanks Mustafa. Don't do a lot of work on this, I'm still figuring out a few details. Just some suggestions for string filters (for example '*_SINK*' maybe for depletions) was what I was wondering, it doesn't have to be a complete list.

Here are some updated observations about these points:
* The infeasibilities in the annual model are not because of the EOP constraints themselves -- they occur in the *next* year because not enough water was carried over. We want the model to still be able to solve in this case, by reducing environmental constraints etc.
* I added an if statement to avoid reducing deadpools. That's not realistic.
* I agree the unit cost approach should work in theory. And most of the time it does work, it's a smart idea. But occasionally this situation happens: debug flow appears at a node where all of the outbound links have zero lower-bounds. Which means that the debug flow is being used to satisfy a constraint further downstream. My impression is that the objective function is dominated by debug flows so moving water on the unit cost links might be a negligible cost for the solver, but I'm not sure. 

Anyway to address that last problem I'm now letting it reduce lower bounds on downstream links up to 5 connections downstream. Because why not. 

Right now, the annual model gets up to WY 1973 without crashing, using a few different levels of carryover requirements. Which is pretty good! Getting there.

**Comment by msdogan** [comment]
Alright, I will give a list of link identifiers then to filter. Okay, that makes sense. Right now unit cost is `$1` I think, and objective function is on the order of billion $, so it might be negligible. Do you think making unit cost something like `10,000$` instead of `1$` would solve the problem? Anyway, just an idea. I will think about that.

**Comment by jdherman** [comment]
Yea I think the ratio between the two costs is important. (The magnitude of debug flows also matters -- Max found if the debug flows are really small, like 10^-6, the debug costs aren't large enough to matter). Thanks Mustafa.

**Comment by jdherman** [comment]
Update: it worked!!! (Annual connected runs with carryover constraints, all 82 years). I ran it for carryover values from 0%-50% in steps of 5%, applied to all surface reservoirs.

More details/plots and code cleanup soon.

**Comment by mfefer** [comment]
Great!!! I just finished the climate multiplier script as well.

**Comment by msdogan** [comment]
@jdherman that's awesome!

Here is a list of links with fixed flows and minimum in-stream flow reqs. I put a list of links that I think okay and not to okay to modify lower or upper bounds.

*****
Okay to modify lower or upper bound:
* Ending storage values for reservoirs `_FINAL` can be modified, if needed.
* Links ending with `_SINK` show losses including local depletion and can be modified.
* Refuge deliveries listed below can be modified.
* Bypass flows, Delta outflow, Delta Cross Channel and Kern River Intertie flows can be modified.
* Any minimum flow req can be modified.

NOT okay to modify upper or lower bound:
* Inflows, starting with `INFLOW_`, are represented as constrained flows but we cannot modify them in the calibration process.
* Initial storage values for reservoirs `INITIAL_` cannot be modified.
* Fixed ag and urban deliveries listed below cannot be modified.
* Reservoir lower and upper bounds cannot be modified, except for `SR_CLE` and `SR_SHA` lower bounds, which represent minimum storage requirements.
*****

Constrained Flows:
```
Region	Link	Type	
5	HU500_AgS: Owens Valley	Ag Delivery
1	D30_N203	Sutter Bypass
1	D61_D61B	Sutter Bypass
2	D66A_N203	Sutter Bypass
2	C20_D55	Yolo Bypass
2	D43_C306	Yolo Bypass
2	D541_Required Delta Outflow	Constrained Flow
2	C7_C20	Yolo Bypass
2	D511_D513	Delta Cross Channel
3	C54_D608	James Bypass
4	C73_D859	Kern River Intertie
1	HSUR101_R-SRW	Refuge Delivery
2	HSUR201_R-GLD	Refuge Delivery
2	HSUR202_R-SUT	Refuge Delivery
3	HSUR301_R-SJE	Refuge Delivery
3	HSUR302_R-SJW	Refuge Delivery
3	HSUR303_R-MDT	Refuge Delivery
4	HSUR401_R-KER	Refuge Delivery
4	HSUR402_R-PIX	Refuge Delivery
1	U102_Ext: CVPM02	Urban Delivery
1	U102_Int: CVPM02	Urban Delivery
1	U103_Ext: CVPM03	Urban Delivery
1	U103_Int: CVPM03	Urban Delivery
1	U104_Ext: CVPM04	Urban Delivery
1	U104_Int: CVPM04	Urban Delivery
2	U206_Ext: CVPM09	Urban Delivery
2	U206_Int: CVPM09	Urban Delivery
2	U202_Ext: CVPM05	Urban Delivery
2	U202_Int: CVPM05	Urban Delivery
2	U203_Ext: CVPM06	Urban Delivery
2	U203_Int: CVPM06	Urban Delivery
3	U303_EXT: CVPM10	Urban Delivery
3	U303_INT: CVPM10	Urban Delivery
4	U404_Ext: CVPM15	Urban Delivery
4	U402_Ext: CVPM14	Urban Delivery
4	U402_Int: CVPM14	Urban Delivery
4	U408_Ext: CVPM19	Urban Delivery
4	U404_Int: CVPM15	Urban Delivery
4	U408_Int: CVPM19	Urban Delivery
4	U409_Ext: CVPM21	Urban Delivery
4	U409_Int: CVPM21	Urban Delivery
```

*****
Minimum in-stream flows:

```
Region	River	Link
		
1	Clear Creek	SR-WHI_D73
1	Sacramento River	D5_D73
1	Sacramento River	D77_D75
1	Sacramento River	D61_C301
1	Stony Creek	SR-BLB_C9
1	Stony Creek	C9_C12
1	Trinity River	D94_Sink D94
2	Bear River	C35_SR-RLL-CMB
2	Bear River	N201_N202
2	Bear River	SR-CFW_C33
2	Bear River	C33_C308
2	American River	D64_C8
2	American River	D9_D85
2	Calaveras River	C41_C42
2	Feather River	C23_C25
2	Feather River	C25_C31
2	Feather River	D42_D43
2	Cosumnes River	C37_C38
2	Sacramento River	D503_D511
2	Sacramento River	D507_D509
2	Yuba River	SR-ENG_C28
2	Yuba River	C83_C31
3	San Joaquin River	D616_C42
3	San Joaquin River	D609_D608
3	Fresno River	D624_C48
3	Merced River	D645_D646
3	Merced River	D649_D695
3	Stanislaus River	D672_D675
3	Stanislaus River	D675_D676
2	Mokelumne River	SR-CMN_C38
3	Tuolumne River	SR-DNP_D662
3	Tuolumne River	D662_D663
5	Mono Basin	SR-GNT_SR-ML
1	Lake Shasta	SR-SHA
1	Lake Trinity	SR-CLE
```

**Comment by msdogan** [comment]
@jdherman @mfefer I have created `abstract_model` branch. Now merging this `concrete` branch to `master`

**Comment by msdogan** [comment]
@jdherman do you want me to keep `concrete` branch or delete it? Thanks

**Comment by jdherman** [comment]
Thanks @msdogan. Since concrete is merged we can delete it.

**Pull request merged**
